[project]
name = "spar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.8",
    "tinker>=0.13.1",
    "tinker-cookbook>=0.1.0",
]
