[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "propensities"
version = "0.1.0"
dependencies = [
    "anthropic",
    "openai",
    "pyyaml",
    "inspect-ai",
    "inspect-viz",
    "tinker",
    "tinker-cookbook",
]